import type { CumulativeResult } from './cgpa';
import { classify } from './cgpa';

export function buildTranscriptHtml(cumulative: CumulativeResult): string {
  let runningUnits = 0;
  let runningQp = 0;

  const semesterBlocks = cumulative.semesters
    .map((sr) => {
      runningUnits += sr.totalUnits;
      runningQp += sr.totalQualityPoints;
      const runningCgpa = runningUnits === 0 ? 0 : runningQp / runningUnits;
      const standing = classify(runningCgpa);

      const rows = sr.rows
        .map(
          (r, i) => `
          <tr class="${r.passed ? '' : 'fail'}">
            <td>${i + 1}</td>
            <td>${escape(r.course.code) || '&mdash;'}</td>
            <td class="left">${escape(r.course.title) || '&mdash;'}</td>
            <td>${r.course.creditUnits}</td>
            <td class="left">${r.course.type === 'CORE/COMPULSORY COURSE' ? 'Core' : 'Elective'}</td>
            <td>${r.course.score}</td>
            <td class="grade">${r.grade}</td>
            <td>${r.qualityPoints}</td>
          </tr>`,
        )
        .join('');

      const outstandings =
        sr.outstandings.length === 0
          ? 'None'
          : sr.outstandings.map((c) => escape(c.code)).join(', ');

      return `
        <section class="semester">
          <h2>${escape(sr.semester.level)} &mdash; ${escape(sr.semester.term)} &mdash; ${escape(sr.semester.session)}</h2>
          <table>
            <thead>
              <tr>
                <th>S/N</th><th>Code</th><th class="left">Title</th>
                <th>Unit</th><th class="left">Type</th><th>Score</th>
                <th>Grade</th><th>Grade Point</th>
              </tr>
            </thead>
            <tbody>
              ${rows}
              <tr class="total">
                <td colspan="3" class="total-label">TOTAL</td>
                <td class="total-value">${sr.totalUnits}</td>
                <td colspan="3"></td>
                <td class="total-value">${sr.totalQualityPoints}</td>
              </tr>
            </tbody>
          </table>
          <table class="summary">
            <tr><td>GPA (Total Grade Point ÷ Total Units)</td><td class="highlight">${sr.totalQualityPoints} ÷ ${sr.totalUnits} = ${sr.gpa.toFixed(2)}</td></tr>
            <tr><td>Semester's CGPA</td><td class="highlight">${runningCgpa.toFixed(2)}</td></tr>
            <tr><td>Outstandings</td><td>${outstandings}</td></tr>
            <tr><td>Academic Standing</td><td>${standing}</td></tr>
          </table>
        </section>`;
    })
    .join('');

  return `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>Academic Transcript</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: -apple-system, system-ui, sans-serif; color: #0B1F3A; margin: 0; padding: 24px; }
  header { text-align: center; margin-bottom: 24px; }
  header h1 { color: #1976FF; margin: 0; font-size: 22px; }
  header p { color: #5A6B85; margin: 4px 0 0; font-size: 12px; }
  .cumulative { background: #1976FF; color: white; padding: 16px; border-radius: 8px; margin-bottom: 24px; }
  .cumulative .label { font-size: 11px; opacity: 0.85; text-transform: uppercase; letter-spacing: 0.5px; }
  .cumulative .value { font-size: 36px; font-weight: 700; margin: 4px 0 12px; }
  .cumulative .meta { display: flex; gap: 24px; font-size: 12px; }
  .cumulative .meta span { opacity: 0.9; }
  .cumulative .meta strong { display: block; font-size: 14px; margin-top: 2px; }
  .semester { margin-bottom: 28px; page-break-inside: avoid; }
  .semester h2 { background: #1976FF; color: white; padding: 8px 12px; font-size: 13px; margin: 0; border-radius: 4px 4px 0 0; }
  table { width: 100%; border-collapse: collapse; font-size: 11px; }
  th, td { border: 1px solid #E1E8F5; padding: 6px 8px; text-align: center; vertical-align: middle; }
  th { background: #EEF3FB; color: #5A6B85; text-transform: uppercase; font-size: 10px; letter-spacing: 0.5px; }
  td.left, th.left { text-align: left; }
  tr.fail td.grade { color: #C62828; font-weight: 700; }
  td.grade { font-weight: 700; color: #1976FF; }
  tr.total { background: #EEF3FB; border-top: 2px solid #1976FF; }
  tr.total td.total-label { text-align: right; font-weight: 700; color: #5A6B85; text-transform: uppercase; font-size: 10px; }
  tr.total td.total-value { font-weight: 700; color: #1976FF; font-size: 12px; }
  table.summary { margin-top: 0; }
  table.summary td { text-align: left; }
  table.summary td:last-child { text-align: right; font-weight: 600; }
  table.summary td.highlight { color: #1976FF; font-size: 13px; }
  footer { margin-top: 32px; text-align: center; font-size: 10px; color: #5A6B85; }
</style>
</head>
<body>
  <header>
    <h1>Academic Transcript</h1>
    <p>Generated by CGPA Calculator</p>
  </header>

  <div class="cumulative">
    <div class="label">Cumulative CGPA</div>
    <div class="value">${cumulative.cgpa.toFixed(2)}</div>
    <div class="meta">
      <span>Total Units<strong>${cumulative.totalUnits}</strong></span>
      <span>Semesters<strong>${cumulative.semesters.length}</strong></span>
      <span>Standing<strong>${cumulative.standing}</strong></span>
    </div>
  </div>

  ${semesterBlocks}

  <footer>Generated ${new Date().toLocaleDateString()}</footer>
</body>
</html>`;
}

function escape(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
